version: '3'

services:
  mongo:
    image: mongo:3
    ports:
      - '27017:27017'
    volumes:
      - './data:/data/db'

  mongo_api:
    build: ./express_mongo_api
    ports:
      - '3100:3100'
    links:
      - mongo

  app:
    build: ./demo-site
    ports:
      - '8080:8080'
